#!/usr/bin/env python3

import requests
import sys

data = """
{
   "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements"
}
"""

url = 'http://localhost:8081/rest/v1/graph/doOperation/get/elements/all'

response = requests.post(url, data,
                         headers={'content-type': 'application/json'})

if response.status_code != 200:
    print("Response code: ", response.status_code)
    sys.exit(1)

obj = response.json()

# Sort so that groups are grouped together
obj = sorted(obj, key=lambda x: x["group"])

for v in obj:
    if "source" in v:
        print("%s --%s--> %s" % (v["source"], v["group"], v["destination"]))


